In [6]:

import numpy as np


x = np.ones((5, 5))

print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0


print(x)


1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
import numpy as np

# Create a 5x5 matrix filled with 3s
matrix = np.full((5, 5), 3)

# Set the first diagonal (1s)
np.fill_diagonal(matrix, 1)

# Set the second diagonal (2s)
np.fill_diagonal(np.fliplr(matrix), 2)

print(matrix)


[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]


In [ ]:
#task 4

In [8]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                     [10, 11, 12]])

# Stack the matrices vertically
stacked_matrix = np.vstack((matrix1, matrix2))

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nStacked Matrix:")
print(stacked_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Stacked Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
